Repository imdaxsz/orday-front-end, pull requests merged in 2023-11, with the labels that each got.

#139 feat: 회원 리뷰 조회, 작성, 수정 구현
  src/api/ReviewApi.ts
  src/components/Header/index.tsx
  src/components/Header/style.ts
  src/hooks/useReivewList.ts
  src/hooks/useWriteReview.ts
  src/routes/Review/List.tsx
  src/routes/Review/Write.tsx
  src/styles/GlobalStyle.tsx
  src/types/global.d.ts
Labels: fix, feature

#142 feat: api 요청 시 로딩 추가
  src/hooks/useEditProfile.ts
  src/hooks/useForm.ts
  src/hooks/useJoin.ts
  src/hooks/useLeave.ts
  src/hooks/useLogin.ts
  src/hooks/useWriteReview.ts
  src/routes/Join.tsx
  src/routes/Login.tsx
  src/routes/MyPage/EditProfile/index.tsx
  src/routes/MyPage/Leave/index.tsx
  src/routes/router/publicRoutes.tsx
Labels: feature

#144 feat: 상품 상세페이지 리뷰 관련 기능 구현
  src/api/ProductApi.ts
  src/api/ReviewApi.ts
  src/components/CommunityCard/Review/Action.tsx
  src/components/Dropdown/index.tsx
  src/components/PostCodeModal.tsx
  src/components/ReviewCard/Action.tsx
  src/components/ReviewCard/Content.tsx
  src/components/ReviewCard/Header.tsx
  src/components/ReviewCard/index.tsx
  src/components/ReviewCard/style.ts
  src/hooks/useProductReviews.ts
  src/hooks/useReviewModal.ts
  src/hooks/useToggleLike.ts
  src/routes/Product/Review/PhotoReviews.tsx
  src/routes/Product/Review/ReviewCard.tsx
  src/routes/Product/Review/ReviewModal.tsx
  src/routes/Product/Review/ReviewRating.tsx
  src/routes/Product/Review/SimpleReviewCard.tsx
  src/routes/Product/Review/index.tsx
  src/routes/Review/RecentReviews.tsx
  src/types/global.d.ts
Labels: feature, refactor

#143 refactor: 상품 상세페이지 관련 코드 리팩토링 및 기능 추가
  src/constants/index.ts
  src/hooks/useProductDetail.ts
  src/routes/Product/Detail.style.ts
  src/routes/Product/Detail.tsx
  src/routes/Product/OptionProduct.tsx
  src/routes/Product/Quantity.style.ts
  src/routes/Product/Quantity.tsx
  src/routes/Product/index.tsx
  src/types/global.d.ts
Labels: feature, refactor

#145 feat: 최신 리뷰 목록 조회 구현
  src/api/ReviewApi.ts
  src/components/ReviewCard/Action.tsx
  src/components/ReviewCard/Content.tsx
  src/components/ReviewCard/Header.tsx
  src/components/ReviewCard/index.tsx
  src/components/ReviewCard/style.ts
  src/hooks/useRecentReviews.ts
  src/routes/Review/RecentReviews.tsx
  src/types/global.d.ts
  src/utils/.gitkeep
  src/utils/index.ts
Labels: feature, refactor

#151 feat: 구글 로그인 구현 및 vercel 배포 404 오류 수정
  src/hooks/useForm.ts
  src/routes/Login.tsx
  src/routes/router/privateRoutes.tsx
Labels: fix, feature

#149 feat: 상품 상세페이지 리뷰가 없을 경우 메시지 추가
  src/routes/Product/Review/index.tsx
Labels: feature

#146 feat: 상품 상세페이지 관련 기능 추가
  src/api/ProductApi.ts
  src/components/ProductCard/index.tsx
  src/components/ReviewCard/Content.tsx
  src/hooks/useProductDetail.ts
  src/hooks/useProductInfo.ts
  src/routes/Order/ProductInfo.tsx
  src/routes/Product/Detail.tsx
  src/routes/Product/OptionProduct.tsx
  src/routes/Product/index.tsx
  src/types/global.d.ts
Labels: feature, refactor

#156 상품 상세 관련 기능 변경 및 조회 요청시 로딩 상태 추가
  src/api/ProductApi.ts
  src/hooks/useProductDetail.ts
  src/hooks/useProductInfo.ts
  src/routes/Product/Detail.tsx
  src/routes/Product/index.tsx
Labels: feature, refactor

#158 refactor: 구글 로그인 및 axios interceptor 로직 수정
  src/components/Header/index.tsx
  src/libs/api/index.ts
  src/routes/Login.tsx
  src/routes/router/privateRoutes.tsx
  src/store/slices/authSlice.ts
Labels: feature, refactor

#161 refactor: 로그아웃 로직 수정
  src/api/AuthApi.ts
  src/hooks/useLogout.ts
Labels: refactor

#162 deploy: 로그아웃 로직 변경 사항 적용
  src/api/AuthApi.ts
  src/hooks/useLogout.ts
Labels: refactor

#160 refactor: 디자인 변경 사항 적용
  src/components/Carousel/style.ts
  src/components/ProductCarousel/style.ts
  src/components/VisualSection/style.ts
  src/routes/Brand/Detail.tsx
Labels: refactor

#165 feat: 구글 로그인 Callback 페이지 추가
  src/routes/Login/OAuthCallback.tsx
  src/routes/Login/index.tsx
  src/routes/router/publicRoutes.tsx
Labels: feature

#169 refactor: 브랜드 목록 조회, 회원 리뷰 목록 조회 로딩 추가
  src/hooks/useBrandList.ts
  src/hooks/useReivewList.ts
  src/routes/Brand/List.tsx
  src/routes/Like/Brand.tsx
  src/routes/Review/List.tsx
Labels: refactor

#163 feat: 주문 내역 조회 관련 기능 구현
  src/api/OrderApi.ts
  src/hooks/useOrderList.ts
  src/routes/MyPage/MyOrder.tsx
  src/routes/MyPage/OrderInfo.style.ts
  src/routes/MyPage/OrderInfo.tsx
  src/routes/MyPage/OrderList/OrderInfo.tsx
  src/routes/MyPage/OrderList/OrderListBox.tsx
  src/routes/MyPage/OrderList/index.tsx
  src/routes/MyPage/index.tsx
  src/routes/router/privateRoutes.tsx
  src/types/global.d.ts
Labels: feature, refactor

#172 feat: 회원 이름 조회 관련 기능 구현
  src/api/AuthApi.ts
  src/routes/MyPage/UserInfo.style.ts
  src/routes/MyPage/UserInfo.tsx
Labels: feature

#174 feat: 주문 내역 상태 표시 및 주문 완료 페이지 변경
  src/api/OrderApi.ts
  src/routes/MyPage/OrderList/OrderInfo.tsx
  src/routes/MyPage/OrderList/OrderListBox.tsx
  src/routes/Order/OrderConfirm.tsx
  src/routes/Order/ProductInfo.tsx
  src/types/global.d.ts
Labels: feature, refactor
