Repository imdaxsz/orday-front-end, pull requests merged in 2023-12, with the labels that each got.

#180 feat: 조회 요청시 로딩 상태 확인
  src/hooks/useLikedList.ts
  src/hooks/useOrderList.ts
  src/hooks/useProductList.ts
  src/routes/Cart/index.tsx
  src/routes/Category.tsx
  src/routes/Like/Products.tsx
  src/routes/MyPage/OrderList/OrderInfo.tsx
  src/routes/Product/index.tsx
  src/store/slices/cartSlice.ts
Labels: feature, refactor

#182 fix: 리뷰 대상 상품 조회 요청 url 수정
  src/api/ProductApi.ts
Labels: fix

#192 refactor: 장바구니 페이지 UI 변경
  src/routes/Cart/ProductItem.tsx
  src/routes/Cart/index.tsx
Labels: feature, refactor

#193 fix: 리뷰 좋아요 개수 버그 수정 및 최신 리뷰 이미지 렌더링 조건 추가
  src/components/ReviewCard/Content.tsx
  src/components/ReviewCard/style.ts
  src/hooks/useToggleLike.ts
Labels: bug, fix

#194 feat: 상품 장바구니 추가시 장바구니 이동 Modal 컴포넌트 구현
  src/hooks/useProductAction.ts
  src/routes/Product/Detail.tsx
Labels: feature

#195 feat: 웹 성능 최적화
  src/components/CheckBox/index.tsx
  src/components/Head/index.tsx
  src/components/Header/index.tsx
  src/components/LikeButton.tsx
  src/routes/Cart/ProductItem.tsx
  src/routes/MyPage/OrderList/OrderListBox.tsx
  src/routes/Order/ProductInfo.tsx
  src/routes/Product/index.tsx
Labels: feature, refactor

#198 refactor: 웹 성능 최적화 및 코드 리팩토링
  src/components/AuthHeader.tsx
  src/components/Carousel/index.tsx
  src/components/ReviewCard/Action.tsx
  src/components/ReviewCard/style.ts
  src/components/SelectBox/index.tsx
  src/components/VisualSection/index.tsx
  src/hooks/useEditProfile.ts
  src/hooks/useJoin.ts
  src/hooks/useToggleLike.ts
  src/routes/Brand/Detail.tsx
  src/routes/Brand/List.tsx
  src/routes/Join.tsx
  src/routes/Login/index.tsx
  src/routes/MyPage/EditProfile/index.tsx
  src/routes/Order/DeliveryInfo.tsx
  src/routes/Order/OrderConfirm.tsx
  src/routes/Product/Review/SimpleReviewCard.tsx
  src/routes/Review/ReviewItem.tsx
Labels: refactor
