Repository imdaxsz/orday-front-end, pull requests merged in 2023-09, with the labels that each got.

#3 feat: 프로젝트 초기 세팅
  .eslintrc.cjs
  .gitignore
  .prettierrc.json
  index.html
  package-lock.json
  package.json
  public/vite.svg
  src/App.tsx
  src/components/.gitkeep
  src/hooks/.gitkeep
  src/main.tsx
  src/routes/.gitkeep
  src/store/.gitkeep
  src/styles/.gitkeep
  src/types/.gitkeep
  src/utils/.gitkeep
  src/vite-env.d.ts
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
Labels: feature

#5 feat: 라우터 기본 설정 #4
  src/App.tsx
  src/main.tsx
Labels: feature

#6 feat: global style
  src/App.tsx
  src/main.tsx
  src/styles/.gitkeep
  src/styles/color.scss
  src/styles/font.scss
  src/styles/reset.scss
  src/styles/style.scss
  src/styles/theme.ts
Labels: feature

#9 feat: Header 컴포넌트
  .gitignore
  package-lock.json
  package.json
  public/logo.svg
  src/App.tsx
  src/components/.gitkeep
  src/components/Header.tsx
  src/components/Icon/DropdownIcon.tsx
  src/components/Icon/DropupIcon.tsx
  src/components/Layout.tsx
  src/components/Menu/MenuItem.tsx
  src/components/Menu/index.tsx
  src/main.tsx
  src/routes/.gitkeep
  src/routes/Home.tsx
  src/styles/GlobalStyle.tsx
  src/styles/color.scss
  src/styles/font.scss
  src/styles/style.scss
  src/styles/theme.ts
Labels: feature, refactor

#12 feat: Button 컴포넌트
  src/components/Button/index.tsx
  src/components/Button/style.ts
  src/styles/styled.d.ts
  src/styles/theme.ts
Labels: feature

#16 feat: Tabs
  src/components/Button/style.ts
  src/components/Tabs/index.tsx
  src/components/Tabs/style.ts
  src/styles/theme.ts
  src/types/.gitkeep
  src/types/index.ts
Labels: feature

#17 feat: CheckBox 컴포넌트
  src/App.tsx
  src/components/CheckBox/index.tsx
  src/components/CheckBox/style.ts
  src/components/Icon/CheckIcon.svg
  src/styles/GlobalStyle.tsx
  src/styles/theme.ts
Labels: feature

#20 feat: 랜딩페이지 일부 퍼블리싱, 상품 카드 컴포넌트 구현
  package-lock.json
  package.json
  src/assets/arrow_drop_down.svg
  src/assets/arrow_drop_up.svg
  src/assets/best.svg
  src/assets/check_icon.svg
  src/assets/new.svg
  src/assets/remove.svg
  src/components/CheckBox/index.tsx
  src/components/CheckBox/style.ts
  src/components/Header.tsx
  src/components/Icon/DropdownIcon.tsx
  src/components/Icon/DropupIcon.tsx
  src/components/Menu/MenuItem.style.ts
  src/components/Menu/MenuItem.tsx
  src/components/Menu/index.tsx
  src/components/Menu/style.ts
  src/components/ProductCard/LikeButton.tsx
  src/components/ProductCard/RemoveButton.tsx
  src/components/ProductCard/index.tsx
  src/components/ProductCard/style.ts
  src/components/VisualSection/index.tsx
  src/components/VisualSection/style.ts
  src/routes/Home.tsx
  src/styles/colors.ts
  src/styles/styled.d.ts
  src/styles/theme.ts
  src/styles/typography.ts
  src/types/index.ts
  tsconfig.json
  vite.config.ts
Labels: feature, refactor, chore

#23 feat: 랜딩 페이지 퍼블리싱
  src/components/Carousel/index.tsx
  src/components/Carousel/style.ts
  src/components/ProductCard/LikeButton.tsx
  src/components/ProductCard/RemoveButton.tsx
  src/components/ProductCard/index.tsx
  src/components/VisualSection/index.tsx
  src/routes/Home.tsx
  src/styles/colors.ts
Labels: fix, feature, refactor

#25 feat: Icon Button
  src/components/Button/index.tsx
  src/components/Button/style.ts
Labels: feature
