Repository imdaxsz/orday-front-end, pull requests merged in 2023-10, with the labels that each got.

#26 feat: 브랜드 상세 페이지 1차 퍼블리싱
  src/App.tsx
  src/components/Button/index.tsx
  src/components/Header.tsx
  src/components/Layout.tsx
  src/components/LikeButton.tsx
  src/components/ProductCard/index.tsx
  src/routes/Brand/Detail.tsx
  src/routes/Brand/List.tsx
Labels: fix, feature, refactor

#30 feat: 카테고리 페이지 구현
  src/App.tsx
  src/assets/chevron_right.svg
  src/components/CategoryNav/index.tsx
  src/components/CategoryNav/style.ts
  src/components/Dropdown/index.tsx
  src/components/Dropdown/style.ts
  src/components/Menu/index.tsx
  src/constants/index.ts
  src/routes/Category.tsx
  src/types/index.ts
Labels: feature

#32 feat: 로그인 페이지 퍼블리싱
  public/favicon.ico
  public/vite.svg
  src/App.tsx
  src/assets/home.svg
  src/assets/logo.svg
  src/assets/logo_typo.svg
  src/components/AuthHeader.tsx
  src/components/Button/style.ts
  src/components/Header.tsx
  src/components/Tabs/index.tsx
  src/components/Tabs/style.ts
  src/components/TextInput/index.tsx
  src/components/TextInput/style.ts
  src/hooks/.gitkeep
  src/hooks/useGuestOrder.ts
  src/routes/Login/GuestOrder.tsx
  src/routes/Login/LoginForm.tsx
  src/routes/Login/index.tsx
Labels: feature

#33 feat: Radio 컴포넌트 구현
  src/components/RadioButton/index.tsx
  src/components/RadioButton/style.ts
  src/styles/colors.ts
Labels: feature

#35 feat: 회원가입 페이지 퍼블리싱 1차
  src/App.tsx
  src/components/Button/style.ts
  src/components/Carousel/style.ts
  src/components/CheckBox/style.ts
  src/components/TextInput/style.ts
  src/main.tsx
  src/routes/Home.tsx
  src/routes/Join.tsx
  src/styles/GlobalStyle.tsx
  src/styles/font.css
  src/styles/typography.ts
Labels: fix, feature

#42 feat: 로그인 페이지 구글 로그인 버튼 추가
  src/routes/Login/LoginForm.tsx
Labels: feature
